Application: 
    name        : simpleApp
    packageName : io.skysail.simple
    path        : generated
    projectName : projectName
    address:
        lines: |
            458 Walkman Dr.
            Suite #292
        city    : Royal Oak
        state   : MI
        postal  : 48046