index(user, messages, converter, model) ::= <<
<!DOCTYPE html>
<html lang="en-gb" dir="ltr">

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>skysail designer application</title>
        <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">
        <link rel="apple-touch-icon-precomposed" href="images/apple-touch-icon.png">
        
        <link rel="stylesheet" href="/static/yootheme/uikit/2.24.3/css/uikit.min.css" />
    <!--     <script src="http://code.jquery.com/jquery-2.2.0.min.js"></script> -->
        <script src="js/uikit.min.js"></script>
        
        <link rel="stylesheet" href="/static/yootheme/uikit/2.24.3/css/uikit.docs.min.css">
<!--        <script src="../vendor/jquery.js"></script>-->
        <script src="/static/yootheme/uikit/2.24.3/js/uikit.min.js"></script>
        <script src="../src/js/components/sticky.js"></script>
        
    </head>

    <body>

        <div class="uk-container uk-container-center uk-margin-top uk-margin-large-bottom">

            <div class="uk-grid" data-uk-grid-margin>
                <div class="uk-width-1-1">
                    <h1 class="uk-heading-large">Documentation</h1>
                    <p class="uk-text-large">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut.</p>
                </div>
            </div>
        </div>
        
        $mainContent(user, converter, messages, model)$
        

    </body>
</html>
>>